version: '3.5'

services:
  php7:
      image: php7-alpine
      container_name: php7
      restart: unless-stopped
      volumes:
        - ./:/var/www/html
        - ./php/php.ini:/usr/local/etc/php/php.ini
      expose:
        - "9000"
      environment:
        - ROOT_PROJECT=/var/www/html/
  nginx7:
      image: nginx:alpine
      container_name: nginx7
      restart: unless-stopped
      volumes:
        - ./nginx/conf/nginx.conf:/etc/nginx/conf/nginx.conf:ro
        - ./nginx/conf.d/php7.conf:/etc/nginx/conf.d/default.conf:ro
        - ./:/var/www/html
      ports:
        - 84:80
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'America/Manaus'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - dbstore:/var/lib/mysql/
    container_name: dbstore

volumes:
  dbstore:
    driver: local