version: '3.3'

services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: 'webstore'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'webstoredoce'
      MYSQL_ROOT_PASSWORD: 'webstoredoce'
      TZ: 'America/Manaus'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - dbstore:/var/lib/mysql/
    container_name: dbstore
volumes:
  dbstore:
    driver: local

   