version: '3.3'

services:
  db:
    image: mysql:5.5
    restart: always
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: 'America/Manaus'
    ports:
      - '3309:3306'
    expose:
      - '3306'
    volumes:
      - dbstore:/var/lib/mysql/
    container_name: dbstore
volumes:
  dbstore:
    driver: local

   
